import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowUpRight, Check, ChevronRight, Circle, Fingerprint, LockKeyhole, ScanSearch, ShieldCheck, Sparkles, Activity, Eye } from 'lucide-react';
import { Button } from '../components/ui/Button';
import Logo from '../assets/Logo.png';

const capabilities = [
    { icon: ScanSearch, title: 'Link intelligence', text: 'Inspect suspicious URLs with signals from 70+ security engines.' },
    { icon: LockKeyhole, title: 'Private by design', text: 'Keep credentials and notes in an AES-256 encrypted personal vault.' },
    { icon: Sparkles, title: 'Human-readable AI', text: 'Understand what a threat means and what to do next.' },
];

const motionItem = { hidden: { opacity: 0, y: 22 }, show: { opacity: 1, y: 0, transition: { duration: 0.55 } } };

export function Landing() {
    return (
        <div className="min-h-screen overflow-hidden bg-[#071014] text-slate-100">
            <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
                <Link to="/" className="flex items-center gap-3"><img src={Logo} alt="SecureMate" className="h-9 w-9" /><span className="text-lg font-bold tracking-tight">SecureMate<span className="text-teal-300">.</span></span></Link>
                <nav className="hidden items-center gap-8 text-sm text-slate-400 md:flex"><a href="#capabilities" className="transition-colors hover:text-white">Capabilities</a><a href="#how-it-works" className="transition-colors hover:text-white">How it works</a><Link to="/demo" className="transition-colors hover:text-white">Try the demo</Link></nav>
                <div className="flex items-center gap-2"><Link to="/login"><Button variant="ghost" size="sm">Sign in</Button></Link><Link to="/register"><Button size="sm" className="bg-teal-300 text-[#071014] hover:bg-teal-200">Get protected <ArrowUpRight className="ml-1 h-4 w-4" /></Button></Link></div>
            </header>

            <main>
                <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-16 lg:grid-cols-[1.02fr_0.98fr] lg:px-8 lg:pb-32 lg:pt-24">
                    <div className="pointer-events-none absolute -left-40 top-0 h-[30rem] w-[30rem] rounded-full bg-teal-400/10 blur-[110px]" />
                    <motion.div initial="hidden" animate="show" transition={{ staggerChildren: 0.1 }} className="relative z-10">
                        <motion.div variants={motionItem} className="mb-7 inline-flex items-center gap-2 rounded-full border border-teal-300/20 bg-teal-300/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-teal-200"><Circle className="h-2 w-2 fill-teal-300 text-teal-300" /> Your digital defense desk</motion.div>
                        <motion.h1 variants={motionItem} className="max-w-2xl text-5xl font-semibold leading-[0.98] tracking-tight text-white sm:text-6xl lg:text-8xl">Know what is <span className="text-teal-300">unsafe.</span></motion.h1>
                        <motion.p variants={motionItem} className="mt-7 max-w-xl text-lg leading-8 text-slate-400">SecureMate turns suspicious links, exposed secrets, and confusing security alerts into clear decisions you can act on.</motion.p>
                        <motion.div variants={motionItem} className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register"><Button size="lg" className="h-13 bg-teal-300 px-6 text-[#071014] hover:bg-teal-200">Start a free scan <ArrowUpRight className="ml-2 h-5 w-5" /></Button></Link><Link to="/demo"><Button size="lg" variant="outline" className="h-13 border-white/15 px-6 text-slate-200 hover:border-teal-300/60 hover:bg-teal-300/5">Explore the live demo <ChevronRight className="ml-2 h-5 w-5" /></Button></Link></motion.div>
                        <motion.div variants={motionItem} className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs text-slate-500">{['No credit card', 'Private vault included', 'Built for everyday use'].map((item) => <span key={item} className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-teal-300" />{item}</span>)}</motion.div>
                    </motion.div>

                    <motion.div initial={{ opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.2 }} className="relative lg:pt-8"><div className="absolute -inset-8 rounded-[2rem] bg-teal-300/5 blur-3xl" /><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#0c1d22] shadow-2xl shadow-black/40"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-2 text-sm font-semibold"><ScanSearch className="h-4 w-4 text-teal-300" /> Link intelligence</div><span className="flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] text-emerald-300"><Circle className="h-2 w-2 fill-emerald-300" /> Live</span></div><div className="p-5 sm:p-7"><p className="mb-3 text-xs uppercase tracking-[0.16em] text-slate-500">Latest analysis</p><div className="rounded-lg border border-white/10 bg-[#071014] p-4 font-mono text-sm text-slate-300">https://invoice-share.co/login</div><div className="mt-6 flex items-center gap-5"><div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-full border-8 border-amber-300/20 border-t-amber-300"><span className="text-2xl font-semibold text-amber-200">62</span></div><div><p className="text-lg font-semibold text-amber-200">Needs attention</p><p className="mt-1 text-sm leading-6 text-slate-400">2 indicators suggest this page may be impersonating a trusted service.</p></div></div><div className="mt-7 space-y-3 border-t border-white/10 pt-5 text-sm">{[[Eye, 'Visual impersonation', 'Detected'], [Fingerprint, 'Domain reputation', 'Review']].map(([Icon, label, state]) => { const ItemIcon = Icon as typeof Eye; return <div key={label as string} className="flex items-center justify-between"><span className="flex items-center gap-3 text-slate-300"><ItemIcon className="h-4 w-4 text-slate-500" />{label as string}</span><span className="text-xs text-amber-200">{state as string}</span></div>; })}</div></div><div className="flex items-center gap-3 border-t border-white/10 bg-white/[0.025] px-5 py-4 text-xs text-slate-500"><Activity className="h-4 w-4 text-teal-300" /> Analysis completed in 4.2 seconds</div></div></motion.div>
                </section>

                <section id="capabilities" className="border-y border-white/10 bg-[#0a181c] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">One calm place</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Security that speaks plainly.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">A focused toolkit for the moments when you need confidence, not another dashboard full of noise.</p></div><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 md:grid-cols-3">{capabilities.map(({ icon: Icon, title, text }) => <div key={title} className="bg-[#0a181c] p-7 transition-colors hover:bg-[#102328]"><Icon className="h-6 w-6 text-teal-300" /><h3 className="mt-8 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></div></section>
+                <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">A better habit</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Pause. Check. Continue.</h2></div><div className="grid gap-8 sm:grid-cols-3">{[['01', 'Paste the link', 'Drop in anything that feels off before opening it.'], ['02', 'Read the signal', 'See the risk score and the evidence behind it.'], ['03', 'Move with confidence', 'Save the report, learn the pattern, or walk away.']].map(([number, title, text]) => <div key={number} className="border-l border-teal-300/30 pl-5"><span className="font-mono text-xs text-teal-300">{number}</span><h3 className="mt-5 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></div></section>
+            </main>
+            <footer className="border-t border-white/10 px-5 py-7 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-xs text-slate-500 sm:flex-row"><span>© {new Date().getFullYear()} SecureMate. Personal security, made clear.</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-teal-300" /> Your privacy stays yours.</span></div></footer>
+        </div>
    );
}
